---
extends: default

rules:
  line-length:
    max: 110

  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: true

  comments:
    min-spaces-from-content: 1

  new-lines:
    type: unix

  trailing-spaces: {}
