---
# Install chezmoi via official install script
- name: Install chezmoi
  become: false
  ansible.builtin.shell: |
    sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
  args:
    creates: /usr/local/bin/chezmoi
