---
# 1) Make sure we can fetch and verify Docker’s packages
- name: Install prerequisites for Docker APT repo
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

# 2) Create keyring directory
- name: Create /etc/apt/keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

# 3) Download and install Docker’s GPG key
- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'
    force: no

# 4) Add the official Docker APT repository
- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu
      {{ ansible_lsb.codename }} stable
    filename: docker
    state: present

# 5) Refresh apt cache now that we have Docker’s repo
- name: Update apt cache (post-repo)
  ansible.builtin.apt:
    update_cache: yes

# 6) Install Docker Engine and related plugins
- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

# 7) Ensure Docker service is enabled and started
- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
